### PR TITLE
Add support for >=PHP5.3

### PR DESCRIPTION
**Pull request by dhyegofernando**
For the people who can't actually choose for PHP 5.5+ we could make this separated branch available.

### CODE REVIEW

**Comment by szepeviktor** [comment]
> (PHP 5 >= 5.5.0, PHP 7)
> password_hash — Creates a password hash

http://php.net/manual/en/function.password-hash.php

**Comment by swalkinshaw** [comment]
We address this in our [FAQ](https://github.com/roots/wp-password-bcrypt#faq).

But I appreciate this PR anyway. It's a good one 👍

**Comment by dhyegofernando** [comment]
@swalkinshaw @szepeviktor Ok, but if you see I'm currently using a polyfill for this with the composer package [ircmaxell/password-compat](https://github.com/ircmaxell/password_compat)

**Comment by swalkinshaw** [comment]
@dhyegofernando yeah I understand. But from our point of view we're talking about security and then supporting really old EOL versions of PHP.

**Comment by dhyegofernando** [comment]
:+1:

**Pull request closed without merging**
