### PR TITLE
Making it WP-style

### PR DESCRIPTION
**Pull request by szepeviktor**
+semver

### CODE REVIEW

**Comment by szepeviktor** [comment]
@ianchanning Maybe like this.

**Comment by ianchanning** [comment]
I don't think it needs semver, the plugin looks pretty good as it is, it just needs to be submitted to the WordPress.org directory and see if they reject it

**Comment by szepeviktor** [comment]
It is already sent&accepted on WP.org: https://github.com/szepeviktor/password-bcrypt
I'll commit it as soon as I get home.

-- 
+36204242498
Ezen a készüléken nehéz gépelni. 
Elnézést!

**Comment by ianchanning** [comment]
Great stuff. Slight change that needs to be made is that the minimum WordPress version should be 4.4, not 4.0 as you've got. Commented here: https://discourse.roots.io/t/improving-wordpress-passwords-security/6074/20?u=benword and this has been added to the master `README.md` too.

**Pull request closed without merging**
